# THe LLM model will be here to generate the. answer of the. query





from .exceptions import LLMError
from dotenv import load_dotenv
import os
from groq import Groq
from logging import getLogger
logger = getLogger(__name__)
load_dotenv()


GROQ_API_KEY = os.getenv("GROQ_API_KEY")

class LLMClient: 
    def __init__(self, api_key):
        """
        Initializes the LLMClient with the provided API key.
        Args:
            api_key (str): The API key for authenticating with the LLM service.
        """
        try:
            if not api_key:
                api_key = GROQ_API_KEY
            self.groq_client = Groq(api_key=api_key)
            logger.info("LLM client initialized successfully.")

        except Exception as e:
            logger.error(f"Error in initializing LLM client: {e}")
            raise LLMError(f"Error in initializing LLM client: {e}")
    

    def build_prompt(self, question, chunks): 
        """
        Builds a prompt for the LLM by combining the question and the relevant chunks.
        Args:
            question (str): The user's question.
            chunks (list): A list of relevant text chunks to be included in the prompt.
        Returns:
            str: The constructed prompt for the LLM.
        """
        try: 
            system_prompt = "You are a helpful research assistant. Answer the user's question based ONLY on the provided context.If the answer cannot be found in the context, say 'I cannot find the answer in the provided document.'Be concise, accurate and directly answer the question."

            user_prompt = f"Question: {question}\n\nContext:\n" + "\n\n".join(chunks)
            logger.info("Prompt built successfully for LLM.")
            return system_prompt , user_prompt
        
        except Exception as e:
            logger.error(f"Error in building prompt for LLM: {e}")
            raise LLMError(f"Error in building prompt for LLM: {e}")
        
        
    def generate_answer(self, question, chunks):
        """
        Generates an answer from the LLM based on the provided prompt.
        Args:
            question (str): The user's question.
            chunks (list): A list of relevant text chunks to be included in the prompt.
        Returns:
            str: The answer generated by the LLM.
        """
        try:
            system_prompt, user_prompt = self.build_prompt(question, chunks)
            response = self.groq_client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ]
            )
            answer = response.choices[0].message.content
            logger.info("Answer generated successfully from LLM.")
            return answer
        
        except Exception as e:
            logger.error(f"Error in generating answer from LLM: {e}")
            raise LLMError(f"Error in generating answer from LLM: {e}")
