# This is the pipline that will process the PDF file, generate embeddings and store them in the vector store. It will also handle the retrieval of relevant chunks based on the query and pass them to the LLM for generating the answer.z


from .pdf_processor import PDFProcessor
from .embeddings import EmbeddingGenerator
from .vector_store import VectorStore
from .llm import LLMClient
from .exceptions import PDFProcessingError, EmbeddingError, VectorStoreError, LLMError
from logging import getLogger
from .exceptions import PipelineError
logger = getLogger(__name__)



class RAGPipeline:
    def __init__(self):
        """
        Initializes the RAGPipeline with the necessary components: PDFProcessor, EmbeddingModel, VectorStore, and LLMClient.
        Args:
            None
        """
        try: 
            self.pdf_processor = PDFProcessor(chunk_size=500, chunk_overlap=50)  # Initialize PDFProcessor with desired chunk size and overlap
            self.embedding_generator = EmbeddingGenerator()
            self.vector_store = VectorStore(dimensions=384)  # Assuming 384-dimensional embeddings for 'all-MiniLM-L6-v2'
            self.llm_client = LLMClient(api_key = None)  # Initialize LLMClient with necessary configuration (e.g., API key)
            logger.info("RAG pipeline initialized successfully.")

        except Exception as e:
            logger.error(f"Error in initializing RAG pipeline: {e}")
            raise PipelineError(f"Error in initializing RAG pipeline: {e}")
        

    def ingest(self, file_path: str): 
        """
        Ingests a PDF file, processes it, generates embeddings, and stores them in the vector stored into FAISS
        Args:
            file_path (str): The path to the PDF file to be ingested.
        """
        try: 
            # Step 1: Extract text from the PDF file
            # Step 2: Clean the extracted text
            # Step 3: Chunk the cleaned text into smaller pieces
            chunks = self.pdf_processor.process(file_path)
            
            
            # Step 4: Generate embeddings for each chunk
            embeddings = self.embedding_generator.generate_batch(chunks)
            
            # Step 5: Store the chunks and their corresponding embeddings in the vector store
            self.vector_store.add_chunks(chunks, embeddings)
            
            logger.info(f"PDF file ingested successfully: {file_path}")

        except (PDFProcessingError, EmbeddingError, VectorStoreError) as e:
            logger.error(f"Error in ingesting PDF file: {e}")
            raise PipelineError(f"Error in ingesting PDF file: {e}")
            

    def query(self, question: str):
        """
        Handles a user query by retrieving relevant chunks from the vector store andgenerating an answer using the LLM.
        Args:
            question (str): The user's question to be answered.
        Returns:
            str: The answer generated by the LLM based on the retrieved chunks.
        """
        try: 
            # Step 1: Generate an embedding for the user's question
            query_embedding = self.embedding_generator.generate(question)
            
            # Step 2: Retrieve relevant chunks from the vector store based on the queryembedding
            relevant_chunks = self.vector_store.search(query_embedding, k=5)  # Retrieve top 5 relevant chunks
                
            # Step 3: Generate an answer using the LLM based on the retrieved chunks
            answer = self.llm_client.generate_answer(question, relevant_chunks)
                
            return answer
            
        except (EmbeddingError, VectorStoreError, LLMError) as e:
            logger.error(f"Error in processing query: {e}")
            raise PipelineError(f"Error in processing query: {e}")


